### ISSUE TITLE
Installation issue in Ubuntu

### ISSUE THREAD

**Issue by vreddhi** [akamai/httpie-edgegrid#16]
Installing in Ubuntu 16.04 LTS results in Segmentation Fault.

**Comment by robertolopezlopez** [comment]
Hi @vreddhi ,

This issue seems fixed already. If you agree, we could close this ticket.

![image](https://user-images.githubusercontent.com/1519467/126494328-e321ec28-d0bb-4d6b-91f8-21bec895a907.png)
![image](https://user-images.githubusercontent.com/1519467/126495991-a8d1157a-e654-456d-b4de-2ecc69424790.png)
![image](https://user-images.githubusercontent.com/1519467/126496058-d762a2c8-daf3-4cbe-b8ad-eb2e04ef5d96.png)

**Comment by robertolopezlopez** [comment]
Hi Vreddhi,

As we have not got any further answer to this issue, I guess that you agree with my comment above :-) thus I will close the issue. Please reopen it if you would like to add more details.

Regards,

Roberto
